// Code generated by internal/ontology/gen from kb/superset/ontology.json. DO NOT EDIT.
// Regenerate: go run ./internal/ontology/gen -ontology <path> -out internal/ontology/symbols.go

package ontology

// OntologyVersion is the version of the ontology these tables were generated from.
const OntologyVersion = "4.0.0"

// NodeType describes one node type from the operad.
type NodeType struct {
	ID, Stratum, URNPattern, URNExample string
	OutPorts, InPorts                   []string
}

// NodeTypes maps a type id to its definition.
var NodeTypes = map[string]NodeType{
	"agent":                 {ID: "agent", Stratum: "S2", URNPattern: "urn:moos:agent:<user>.<name>", URNExample: "urn:moos:agent:sam.claude-code", OutPorts: []string{"connects-to", "participates"}, InPorts: []string{"governed-by"}},
	"agent_session":         {ID: "agent_session", Stratum: "S2", URNPattern: "urn:moos:session:<date>.<agent>", URNExample: "", OutPorts: []string{"focus", "reads"}, InPorts: []string{"participant"}},
	"calendar_event":        {ID: "calendar_event", Stratum: "S2", URNPattern: "urn:moos:cal:<date>.<slug>", URNExample: "", OutPorts: []string{"causes", "anchors"}, InPorts: []string{"daily-summary"}},
	"capability":            {ID: "capability", Stratum: "S1", URNPattern: "urn:moos:capability:<principal>.<name>", URNExample: "urn:moos:capability:sam.writer.messaging", OutPorts: nil, InPorts: []string{"attached-to"}},
	"channel":               {ID: "channel", Stratum: "S2", URNPattern: "urn:moos:channel:<kind>.<slug>", URNExample: "urn:moos:channel:messaging.whatsapp-sam", OutPorts: []string{"provides-kb", "emits"}, InPorts: []string{"owned-by"}},
	"claim":                 {ID: "claim", Stratum: "S2", URNPattern: "urn:moos:claim:<ki-slug>.<index>", URNExample: "urn:moos:claim:yt.we-must-add-structure.01", OutPorts: []string{"tagged"}, InPorts: []string{"asserted-in"}},
	"classification_scheme": {ID: "classification_scheme", Stratum: "S2", URNPattern: "urn:moos:scheme:<taxonomy-id>", URNExample: "urn:moos:scheme:lcc", OutPorts: []string{"classifies"}, InPorts: []string{"mapped-from", "mapped-to"}},
	"clock":                 {ID: "clock", Stratum: "S2", URNPattern: "urn:moos:clock:<owner>.<slug>", URNExample: "", OutPorts: []string{"ticks-on", "keeps-time-with"}, InPorts: []string{"keeps-time-with"}},
	"compute":               {ID: "compute", Stratum: "S2", URNPattern: "urn:moos:compute:<workstation>.<type>", URNExample: "urn:moos:compute:hp-laptop.cpu", OutPorts: []string{"bound-to"}, InPorts: []string{"contained-in", "computed-by"}},
	"crosswalk":             {ID: "crosswalk", Stratum: "S2", URNPattern: "urn:moos:crosswalk:<source>-<target>", URNExample: "urn:moos:crosswalk:lcc-dewey", OutPorts: []string{"maps-from", "maps-to"}, InPorts: nil},
	"derivation":            {ID: "derivation", Stratum: "S2", URNPattern: "urn:moos:derivation:<session-slug>.<seq>", URNExample: "urn:moos:derivation:cowork-z440.glossary-h2-chunker", OutPorts: []string{"produces", "consumes"}, InPorts: []string{"authored-by"}},
	"domain_tag":            {ID: "domain_tag", Stratum: "S2", URNPattern: "urn:moos:tag:<taxonomy>.<slug>", URNExample: "urn:moos:tag:arxiv.math-ct", OutPorts: nil, InPorts: []string{"tagged-in"}},
	"endpoint":              {ID: "endpoint", Stratum: "S2", URNPattern: "urn:moos:endpoint:<workstation>.<kernel>.<port>", URNExample: "urn:moos:endpoint:hp-laptop.primary.8000", OutPorts: []string{"implements"}, InPorts: []string{"exposed-by", "connected-to"}},
	"event_notice":          {ID: "event_notice", Stratum: "", URNPattern: "urn:moos:event:<source>.<id>", URNExample: "", OutPorts: nil, InPorts: nil},
	"external_op":           {ID: "external_op", Stratum: "S2", URNPattern: "urn:moos:external_op:<owner>.<slug>", URNExample: "urn:moos:external_op:sam.mtdc-kernel-start", OutPorts: nil, InPorts: nil},
	"gate":                  {ID: "gate", Stratum: "S2", URNPattern: "urn:moos:gate:<slug>", URNExample: "urn:moos:gate:require-approval", OutPorts: []string{"guards"}, InPorts: nil},
	"git_issue":             {ID: "git_issue", Stratum: "S2", URNPattern: "urn:moos:issue:<repo>.<number>", URNExample: "urn:moos:issue:moos-config.1", OutPorts: []string{"tracks", "depends-on"}, InPorts: []string{"produced-by", "depended-by", "composed-by"}},
	"governance_proposal":   {ID: "governance_proposal", Stratum: "S0-S2", URNPattern: "urn:moos:proposal:<user>.<slug>", URNExample: "urn:moos:proposal:sam.add-gpu-stratum", OutPorts: []string{"promotes-to"}, InPorts: nil},
	"grammar_fragment":      {ID: "grammar_fragment", Stratum: "S1", URNPattern: "urn:moos:grammar_fragment:<slug>", URNExample: "urn:moos:grammar_fragment:view-filter-pin-port", OutPorts: nil, InPorts: nil},
	"group":                 {ID: "group", Stratum: "S2", URNPattern: "urn:moos:group:<slug>", URNExample: "", OutPorts: []string{"owns", "delegates-to"}, InPorts: []string{"member-of", "governed-by"}},
	"guard":                 {ID: "guard", Stratum: "S2", URNPattern: "urn:moos:guard:<slug>", URNExample: "urn:moos:guard:feed-is-active", OutPorts: []string{"guards"}, InPorts: nil},
	"harness":               {ID: "harness", Stratum: "S2", URNPattern: "urn:moos:harness:<owner>.<slug>", URNExample: "urn:moos:harness:sam.claude-code-stdio", OutPorts: []string{"hosts-agent", "provides-tool"}, InPorts: []string{"hosted-by", "runs-workflow"}},
	"kernel":                {ID: "kernel", Stratum: "S2", URNPattern: "urn:moos:kernel:<workstation>.<name>", URNExample: "urn:moos:kernel:hp-laptop.primary", OutPorts: []string{"exposes", "computes-on", "persisted-in"}, InPorts: []string{"hosted-on", "kb-source"}},
	"knowledge_item":        {ID: "knowledge_item", Stratum: "S2", URNPattern: "urn:moos:ki:<source-type>.<slug>", URNExample: "urn:moos:ki:yt.we-must-add-structure-to-deep-learning", OutPorts: []string{"asserts", "tagged"}, InPorts: []string{"produced-by"}},
	"language":              {ID: "language", Stratum: "S1", URNPattern: "urn:moos:language:<name>", URNExample: "", OutPorts: nil, InPorts: nil},
	"manifold":              {ID: "manifold", Stratum: "S2", URNPattern: "urn:moos:manifold:<slug>", URNExample: "urn:moos:manifold:my-tiny-data-collider", OutPorts: nil, InPorts: nil},
	"message_packet":        {ID: "message_packet", Stratum: "", URNPattern: "urn:moos:message:<user>.<session>.<id>", URNExample: "", OutPorts: nil, InPorts: nil},
	"network_endpoint":      {ID: "network_endpoint", Stratum: "S1", URNPattern: "urn:moos:network_endpoint:<host>.<port>", URNExample: "urn:moos:network_endpoint:hp-laptop.8000", OutPorts: nil, InPorts: nil},
	"package":               {ID: "package", Stratum: "S1", URNPattern: "urn:moos:package:<name>", URNExample: "", OutPorts: nil, InPorts: nil},
	"pattern":               {ID: "pattern", Stratum: "S1", URNPattern: "urn:moos:pattern:<slug>", URNExample: "urn:moos:pattern:ki-to-claim-extract", OutPorts: nil, InPorts: nil},
	"prg_task":              {ID: "prg_task", Stratum: "S2", URNPattern: "urn:moos:prg:<id>", URNExample: "", OutPorts: []string{"depends-on", "summarizes"}, InPorts: []string{"anchor", "participant", "child", "daily-summary", "depended-by"}},
	"program":               {ID: "program", Stratum: "S2", URNPattern: "urn:moos:program:<owner>.<slug>", URNExample: "urn:moos:program:sam.t162-presentation", OutPorts: []string{"depends-on", "blocks", "produces", "scheduled-after"}, InPorts: []string{"child", "depended-by", "blocked-by", "produced-by", "scheduled-before", "participant"}},
	"protocol":              {ID: "protocol", Stratum: "S1", URNPattern: "urn:moos:protocol:<name>", URNExample: "", OutPorts: nil, InPorts: nil},
	"purpose":               {ID: "purpose", Stratum: "S2", URNPattern: "urn:moos:purpose:<subject>.<slug>", URNExample: "urn:moos:purpose:sam.t164-tie-the-room-together", OutPorts: []string{"steers", "composes"}, InPorts: []string{"declared-by"}},
	"reactor":               {ID: "reactor", Stratum: "S2", URNPattern: "urn:moos:reactor:<slug>", URNExample: "urn:moos:reactor:extract-claims", OutPorts: []string{"emits"}, InPorts: []string{"triggered-by"}},
	"repository":            {ID: "repository", Stratum: "S2", URNPattern: "urn:moos:repo:<owner>.<name>", URNExample: "urn:moos:repo:msd21091969.moos-kernel", OutPorts: []string{"contains", "produces"}, InPorts: []string{"child", "hosted-on"}},
	"role":                  {ID: "role", Stratum: "S1", URNPattern: "urn:moos:role:<name>", URNExample: "urn:moos:role:lead", OutPorts: nil, InPorts: []string{"granted-by"}},
	"router":                {ID: "router", Stratum: "S1", URNPattern: "urn:moos:router:<name>", URNExample: "urn:moos:router:collider-gateway", OutPorts: nil, InPorts: nil},
	"runtime":               {ID: "runtime", Stratum: "S1", URNPattern: "urn:moos:runtime:<name>", URNExample: "", OutPorts: nil, InPorts: nil},
	"session":               {ID: "session", Stratum: "S2", URNPattern: "urn:moos:session:<kernel-short> | urn:moos:session:<owner-short>.<purpose-slug>", URNExample: "urn:moos:session:hp-z440.primary", OutPorts: []string{"focus", "on"}, InPorts: []string{"participated-by"}},
	"shard_rule":            {ID: "shard_rule", Stratum: "S1", URNPattern: "urn:moos:shard:<name>", URNExample: "urn:moos:shard:feeds-to-hp-laptop", OutPorts: nil, InPorts: nil},
	"skill":                 {ID: "skill", Stratum: "S1", URNPattern: "urn:moos:skill:<slug>", URNExample: "urn:moos:skill:graph-operad-reasoning", OutPorts: nil, InPorts: nil},
	"source_feed":           {ID: "source_feed", Stratum: "S2", URNPattern: "urn:moos:feed:<slug>", URNExample: "urn:moos:feed:yt.mlst", OutPorts: []string{"produces", "implements"}, InPorts: []string{"child"}},
	"storage":               {ID: "storage", Stratum: "S2", URNPattern: "urn:moos:storage:<workstation>.<name>", URNExample: "urn:moos:storage:hp-laptop.local-fs", OutPorts: []string{"synced-via", "provides-kb", "bound-to"}, InPorts: []string{"contained-in", "persists", "sync-target"}},
	"stratum":               {ID: "stratum", Stratum: "S1", URNPattern: "urn:moos:stratum:<name>", URNExample: "", OutPorts: nil, InPorts: nil},
	"system_instruction":    {ID: "system_instruction", Stratum: "S2", URNPattern: "urn:moos:system_instruction:<owner>.<slug>", URNExample: "", OutPorts: []string{"projected-to"}, InPorts: []string{"context-for"}},
	"t_hook":                {ID: "t_hook", Stratum: "S2", URNPattern: "urn:moos:t_hook:<owner_slug>.<slug>", URNExample: "urn:moos:t_hook:ki.my-item.on-status-mutate", OutPorts: nil, InPorts: []string{"watched-by"}},
	"tool_call":             {ID: "tool_call", Stratum: "", URNPattern: "urn:moos:tool_call:<user>.<session>.<id>", URNExample: "", OutPorts: nil, InPorts: nil},
	"tool_result":           {ID: "tool_result", Stratum: "", URNPattern: "urn:moos:tool_result:<user>.<session>.<id>", URNExample: "", OutPorts: nil, InPorts: nil},
	"transport_binding":     {ID: "transport_binding", Stratum: "S2", URNPattern: "urn:moos:transport_binding:<kernel>.<protocol>", URNExample: "", OutPorts: []string{"implements"}, InPorts: []string{"exposed-by"}},
	"twin_link":             {ID: "twin_link", Stratum: "S2", URNPattern: "urn:moos:twin_link:<local_slug>.<remote_slug>", URNExample: "urn:moos:twin_link:hp-laptop.mtdc", OutPorts: []string{"synced-via"}, InPorts: []string{"sync-target"}},
	"user":                  {ID: "user", Stratum: "S2", URNPattern: "urn:moos:user:<name>", URNExample: "urn:moos:user:sam", OutPorts: []string{"owns", "governs"}, InPorts: nil},
	"view_filter":           {ID: "view_filter", Stratum: "S2", URNPattern: "urn:moos:view_filter:<user>.<name>", URNExample: "urn:moos:view_filter:sam.important-programs", OutPorts: []string{"filters-session"}, InPorts: []string{"filtered-by"}},
	"watcher":               {ID: "watcher", Stratum: "S2", URNPattern: "urn:moos:watcher:<slug>", URNExample: "urn:moos:watcher:raw-ki-detector", OutPorts: []string{"triggers"}, InPorts: []string{"watches", "guarded-by"}},
	"workflow":              {ID: "workflow", Stratum: "S1", URNPattern: "urn:moos:workflow:<slug>", URNExample: "urn:moos:workflow:daily-ki-ingest", OutPorts: nil, InPorts: nil},
	"workstation":           {ID: "workstation", Stratum: "S2", URNPattern: "urn:moos:workstation:<name>", URNExample: "urn:moos:workstation:hp-laptop", OutPorts: []string{"hosts", "contains"}, InPorts: []string{"child"}},
}

// NodeTypeIDs is the sorted list of all node type ids.
var NodeTypeIDs = []string{"agent", "agent_session", "calendar_event", "capability", "channel", "claim", "classification_scheme", "clock", "compute", "crosswalk", "derivation", "domain_tag", "endpoint", "event_notice", "external_op", "gate", "git_issue", "governance_proposal", "grammar_fragment", "group", "guard", "harness", "kernel", "knowledge_item", "language", "manifold", "message_packet", "network_endpoint", "package", "pattern", "prg_task", "program", "protocol", "purpose", "reactor", "repository", "role", "router", "runtime", "session", "shard_rule", "skill", "source_feed", "storage", "stratum", "system_instruction", "t_hook", "tool_call", "tool_result", "transport_binding", "twin_link", "user", "view_filter", "watcher", "workflow", "workstation"}

// WF describes one rewrite category (WF01..WF21).
type WF struct {
	ID, Name, Description               string
	AllowedRewrites, SrcTypes, TgtTypes []string
	PortPairs                           [][2]string
}

// WFs maps a WF id to its definition.
var WFs = map[string]WF{
	"WF01": {ID: "WF01", Name: "Ownership", Description: "Principal owns workstation, kernel, or storage.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"user", "group"}, TgtTypes: []string{"workstation", "kernel", "storage", "program", "repository", "session", "purpose", "channel", "agent"}, PortPairs: [][2]string{{"owns", "child"}, {"owns", "owned-by"}}},
	"WF02": {ID: "WF02", Name: "Governance", Description: "Principal governs delegate with delegated role and capabilities.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"user", "role", "group"}, TgtTypes: []string{"agent", "role", "capability"}, PortPairs: [][2]string{{"governs", "governed-by"}, {"delegates-to", "delegated-by"}}},
	"WF03": {ID: "WF03", Name: "Hosting", Description: "Workstation hosts a kernel.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"workstation"}, TgtTypes: []string{"kernel"}, PortPairs: [][2]string{{"hosts", "hosted-on"}}},
	"WF04": {ID: "WF04", Name: "Containment", Description: "Workstation contains compute or storage.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"workstation"}, TgtTypes: []string{"compute", "storage"}, PortPairs: [][2]string{{"contains", "contained-in"}}},
	"WF05": {ID: "WF05", Name: "Exposure", Description: "Kernel exposes a network endpoint.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"kernel"}, TgtTypes: []string{"endpoint"}, PortPairs: [][2]string{{"exposes", "exposed-by"}}},
	"WF06": {ID: "WF06", Name: "Connection", Description: "Agent connects to a kernel endpoint or repository. For repositories: expresses that this agent works in / has access to that repo.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"agent"}, TgtTypes: []string{"endpoint", "repository"}, PortPairs: [][2]string{{"connects-to", "connected-to"}}},
	"WF07": {ID: "WF07", Name: "Workflow lifecycle", Description: "Participation, focus, anchoring, and status changes across sessions, PRGs, and calendar events. The workflow-colored WF.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"agent", "user", "agent_session", "calendar_event", "prg_task", "program", "git_issue"}, TgtTypes: []string{"session", "agent_session", "prg_task", "calendar_event", "program", "git_issue"}, PortPairs: [][2]string{{"participates", "participated-by"}, {"anchors", "anchor"}}},
	"WF08": {ID: "WF08", Name: "Substrate binding", Description: "Compute or storage is physically bound to workstation.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"compute", "storage"}, TgtTypes: []string{"workstation"}, PortPairs: [][2]string{{"bound-to", "binds"}}},
	"WF09": {ID: "WF09", Name: "Compute attachment", Description: "Kernel routes operations to compute substrates.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"kernel"}, TgtTypes: []string{"compute"}, PortPairs: [][2]string{{"computes-on", "computed-by"}}},
	"WF10": {ID: "WF10", Name: "Persistence", Description: "Kernel's rewrite log persists in a storage resource.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"kernel"}, TgtTypes: []string{"storage"}, PortPairs: [][2]string{{"persisted-in", "persists"}}},
	"WF11": {ID: "WF11", Name: "Sync", Description: "Local storage syncs to/from a remote storage.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"storage"}, TgtTypes: []string{"storage"}, PortPairs: [][2]string{{"synced-via", "sync-target"}}},
	"WF12": {ID: "WF12", Name: "KB provision and hydration", Description: "Knowledge base provision: storage→kernel boot hydration, source_feed→knowledge_item production, channel→knowledge_item/message_packet ingestion, knowledge_item→claim extraction, tagging to domain_tags, and classification via scheme/crosswalk nodes.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"storage", "source_feed", "channel", "knowledge_item", "claim", "domain_tag", "classification_scheme", "crosswalk"}, TgtTypes: []string{"kernel", "knowledge_item", "message_packet", "claim", "domain_tag", "classification_scheme", "crosswalk"}, PortPairs: [][2]string{{"provides-kb", "kb-source"}}},
	"WF13": {ID: "WF13", Name: "Promotion", Description: "Governance proposal targets storage/kernel for canonicalization.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"governance_proposal"}, TgtTypes: []string{"storage", "kernel"}, PortPairs: [][2]string{{"promotes-to", "promotion-target"}}},
	"WF14": {ID: "WF14", Name: "Implementation", Description: "Agent, kernel, or endpoint implements a protocol, language, capability, runtime, or package.", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"agent", "kernel", "endpoint"}, TgtTypes: []string{"protocol", "language", "capability", "runtime", "package"}, PortPairs: [][2]string{{"implements", "implemented-by"}}},
	"WF15": {ID: "WF15", Name: "Semantic (open)", Description: "Open semantic relation. Allowed only with explicit port names AND a contract_schema reference.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"*"}, TgtTypes: []string{"*"}, PortPairs: [][2]string{{"{semantic}", "{semantic}"}}},
	"WF16": {ID: "WF16", Name: "Federation", Description: "Routing and connectivity for distributed kernel instances. Router reads shard_rules to route rewrites. Kernels expose endpoints. Shard_rules map URN prefixes to kernel instances.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"router", "kernel", "shard_rule"}, TgtTypes: []string{"kernel", "endpoint", "shard_rule", "router"}, PortPairs: [][2]string{{"routes-to", "routed-from"}}},
	"WF17": {ID: "WF17", Name: "Reactive", Description: "Watch/React/Guard pipeline. Watchers observe the rewrite log, trigger reactors when patterns match. Guards gate reactors with state predicates. The firestarter on the carpet.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"watcher", "reactor", "guard", "t_hook", "gate"}, TgtTypes: []string{"reactor", "watcher", "guard", "t_hook"}, PortPairs: [][2]string{{"triggers", "triggered-by"}}},
	"WF18": {ID: "WF18", Name: "Program composition", Description: "Wires program nodes to their constituent tasks, outputs, sessions, purposes, and sub-programs. Temporal dependency DAG. Known-node dependencies use LINK directly; property-pattern dependencies use WF17 watchers that fire when ANY node matching a filter achieves required properties.", AllowedRewrites: []string{"LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"program", "purpose"}, TgtTypes: []string{"prg_task", "knowledge_item", "agent_session", "program", "git_issue", "repository", "session", "purpose", "channel"}, PortPairs: [][2]string{{"composes", "composed-by"}}},
	"WF19": {ID: "WF19", Name: "Session governance", Description: "Opens, maintains, transfers, and closes session occupancy of kernels by agent delegates. Session is a monoid over kernel occupancy: empty session is identity, sequential claims compose. WF19 gates occupancy against WF02 capability scope (a delegate cannot open a session on a kernel whose owner's capability does not grant required WF categories). Complements WF07, which tracks participation; WF19 tracks kernel OCCUPANCY. Sovereign by kernel — sessions are local-only. Added T=164.", AllowedRewrites: []string{"ADD", "LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"session", "agent", "agent_session"}, TgtTypes: []string{"kernel", "session", "agent_session", "user", "agent"}, PortPairs: [][2]string{{"opens-on", "occupied-by"}, {"has-occupant", "is-occupant-of"}, {"pins-urn", "pinned-by-session"}, {"filtered-by", "filters-session"}, {"mounts-tool", "tool-mounted-in-session"}, {"has-purpose", "purpose-of-session"}}},
	"WF20": {ID: "WF20", Name: "Grammar promotion", Description: "Carries the S4→S1 adjoint `Promote` functor. Admin-authored rewrites that ADD grammar_fragment nodes citing S4 (system_instruction) or S2 (governance_proposal) evidence, then MUTATE their status (proposed → rejected | promoted | merged). When a fragment reaches status=merged, the next ontology baseline version bumps and the fragment's specification is folded into the canonical ontology. Added v3.9 per audit §F and s1_superset_doctrine_reference.", AllowedRewrites: []string{"ADD", "LINK", "UNLINK", "MUTATE"}, SrcTypes: []string{"system_instruction", "governance_proposal"}, TgtTypes: []string{"grammar_fragment"}, PortPairs: [][2]string{{"promotes", "promoted-from"}}},
	"WF21": {ID: "WF21", Name: "causes", Description: "", AllowedRewrites: []string{"LINK", "UNLINK"}, SrcTypes: []string{"derivation", "claim", "knowledge_item", "program", "task", "knowledge_artifact"}, TgtTypes: []string{"derivation", "claim", "knowledge_item", "program", "task", "knowledge_artifact", "channel", "clock"}, PortPairs: [][2]string{{"causes", "caused-by"}}},
}

// WFOrder is the WF ids in declaration order (WF01..WF21).
var WFOrder = []string{"WF01", "WF02", "WF03", "WF04", "WF05", "WF06", "WF07", "WF08", "WF09", "WF10", "WF11", "WF12", "WF13", "WF14", "WF15", "WF16", "WF17", "WF18", "WF19", "WF20", "WF21"}

// PortColors is the set of port colors.
var PortColors = []string{"auth", "topology", "transport", "compute", "storage", "workflow", "semantic", "projection"}

// PortColorMatrix[src][tgt] is one of: "true", "false", "wf15_only", "sink_only".
var PortColorMatrix = map[string]map[string]string{
	"auth":       {"auth": "true", "compute": "false", "projection": "sink_only", "semantic": "wf15_only", "storage": "false", "topology": "true", "transport": "false", "workflow": "false"},
	"compute":    {"auth": "false", "compute": "true", "projection": "sink_only", "semantic": "wf15_only", "storage": "false", "topology": "true", "transport": "false", "workflow": "false"},
	"projection": {"auth": "false", "compute": "false", "projection": "false", "semantic": "false", "storage": "false", "topology": "false", "transport": "false", "workflow": "false"},
	"semantic":   {"auth": "true", "compute": "true", "projection": "sink_only", "semantic": "true", "storage": "true", "topology": "true", "transport": "true", "workflow": "true"},
	"storage":    {"auth": "false", "compute": "false", "projection": "sink_only", "semantic": "wf15_only", "storage": "true", "topology": "true", "transport": "false", "workflow": "false"},
	"topology":   {"auth": "false", "compute": "false", "projection": "sink_only", "semantic": "wf15_only", "storage": "false", "topology": "true", "transport": "false", "workflow": "false"},
	"transport":  {"auth": "false", "compute": "false", "projection": "sink_only", "semantic": "wf15_only", "storage": "false", "topology": "false", "transport": "true", "workflow": "false"},
	"workflow":   {"auth": "false", "compute": "false", "projection": "sink_only", "semantic": "wf15_only", "storage": "false", "topology": "false", "transport": "false", "workflow": "true"},
}

// UseVocab maps a canonical term to its definition.
var UseVocab = map[string]string{
	"_urn_suffix":      "single node reference property (not: _ref)",
	"_urns_suffix":     "plural node reference property (not: _refs)",
	"engine":           "v4.0 canonical alias of `kernel` (D6 — re-ratified T=239 from `instance`): the mo:os **engine** (`engine := fold(log)`, model-theoretic). Canonical type-id/URN stay `kernel` until the gated 4.0.x rewrite. (`instance` = now-deprecated prior alias.)",
	"interaction_node": "discrete interaction artifact node (not: transition, event, message)",
	"manifold":         "top-category node (v4.0, D1) — an application/domain topology; the colimit of branch-episodes sharing one purpose-slug; e.g. manifold:my-tiny-data-collider",
	"node":             "identity point in graph (not: object, element, vertex)",
	"operad":           "valid composition rules / type registry (not: schema, grammar)",
	"persona":          "v4.0 (D3) — a derived presentational identity `persona = Φ(purpose)`, carried as a `derivation`; NOT a node-type and never an authority principal",
	"port":             "interface point on a node type (not: slot, endpoint)",
	"property":         "typed key-value on a node (not: field, payload, attribute)",
	"relation":         "typed connection between nodes (not: binding, edge, wire, association)",
	"rewrite":          "graph transformation operation (not: morphism for the op, update, mutation)",
	"rewrite_category": "family of allowed rewrites WF01-WF15 (not: named relation, UML association)",
	"workspace":        "v4.0 alias of `session` (D2) — same node; canonical type-id/URN stay `session` until the gated 4.0.x rewrite",
}

// ForbiddenVocab maps a forbidden token to the full nomenclature entry it came from.
var ForbiddenVocab = map[string]string{
	"_ref":       "_ref/_refs (as property suffix)",
	"_refs":      "_ref/_refs (as property suffix)",
	"binding":    "binding (for graph)",
	"edge":       "edge",
	"kind":       "kind",
	"morphism":   "morphism (for the wire)",
	"object":     "object",
	"payload":    "payload",
	"schema":     "schema (for operad)",
	"transition": "transition (for interaction nodes)",
}

// Invariants maps CI ids (CI1..CI5) to their statements.
var Invariants = map[string]string{
	"CI1": "Church-Rosser: M_a;M_b = M_b;M_a when affected(M_a) intersect affected(M_b) = empty",
	"CI2": "Projection naturality (structure-preserving only): Project(Apply(M,S)) = Apply(M', Project(S)) for projections with declared rewrite correspondence",
	"CI3": "Identity stability: forall M forall x: urn(M(x)) = urn(x)",
	"CI4": "Log replay determinism: fold(log[0..t]) is deterministic — same log -> same state",
	"CI5": "Rewrite category stability: permitted rewrite categories do not change under rewrites — only governance changes the operad",
}

// RewriteTypes is the four-rewrite opcode set.
var RewriteTypes = []string{"ADD", "LINK", "MUTATE", "UNLINK"}

// SrcPortToWF maps a source port name to the first WF that declares it.
var SrcPortToWF = map[string]string{
	"anchors":      "WF07",
	"bound-to":     "WF08",
	"causes":       "WF21",
	"composes":     "WF18",
	"computes-on":  "WF09",
	"connects-to":  "WF06",
	"contains":     "WF04",
	"delegates-to": "WF02",
	"exposes":      "WF05",
	"filtered-by":  "WF19",
	"governs":      "WF02",
	"has-occupant": "WF19",
	"has-purpose":  "WF19",
	"hosts":        "WF03",
	"implements":   "WF14",
	"mounts-tool":  "WF19",
	"opens-on":     "WF19",
	"owns":         "WF01",
	"participates": "WF07",
	"persisted-in": "WF10",
	"pins-urn":     "WF19",
	"promotes":     "WF20",
	"promotes-to":  "WF13",
	"provides-kb":  "WF12",
	"routes-to":    "WF16",
	"synced-via":   "WF11",
	"triggers":     "WF17",
	"{semantic}":   "WF15",
}

// KnownPorts is the set of all port names appearing in the operad.
var KnownPorts = map[string]bool{
	"anchor":                  true,
	"anchors":                 true,
	"asserted-in":             true,
	"asserts":                 true,
	"attached-to":             true,
	"authored-by":             true,
	"binds":                   true,
	"blocked-by":              true,
	"blocks":                  true,
	"bound-to":                true,
	"caused-by":               true,
	"causes":                  true,
	"child":                   true,
	"classifies":              true,
	"composed-by":             true,
	"composes":                true,
	"computed-by":             true,
	"computes-on":             true,
	"connected-to":            true,
	"connects-to":             true,
	"consumes":                true,
	"contained-in":            true,
	"contains":                true,
	"context-for":             true,
	"daily-summary":           true,
	"declared-by":             true,
	"delegated-by":            true,
	"delegates-to":            true,
	"depended-by":             true,
	"depends-on":              true,
	"emits":                   true,
	"exposed-by":              true,
	"exposes":                 true,
	"filtered-by":             true,
	"filters-session":         true,
	"focus":                   true,
	"governed-by":             true,
	"governs":                 true,
	"granted-by":              true,
	"guarded-by":              true,
	"guards":                  true,
	"has-occupant":            true,
	"has-purpose":             true,
	"hosted-by":               true,
	"hosted-on":               true,
	"hosts":                   true,
	"hosts-agent":             true,
	"implemented-by":          true,
	"implements":              true,
	"is-occupant-of":          true,
	"kb-source":               true,
	"keeps-time-with":         true,
	"mapped-from":             true,
	"mapped-to":               true,
	"maps-from":               true,
	"maps-to":                 true,
	"member-of":               true,
	"mounts-tool":             true,
	"occupied-by":             true,
	"on":                      true,
	"opens-on":                true,
	"owned-by":                true,
	"owns":                    true,
	"participant":             true,
	"participated-by":         true,
	"participates":            true,
	"persisted-in":            true,
	"persists":                true,
	"pinned-by-session":       true,
	"pins-urn":                true,
	"produced-by":             true,
	"produces":                true,
	"projected-to":            true,
	"promoted-from":           true,
	"promotes":                true,
	"promotes-to":             true,
	"promotion-target":        true,
	"provides-kb":             true,
	"provides-tool":           true,
	"purpose-of-session":      true,
	"reads":                   true,
	"routed-from":             true,
	"routes-to":               true,
	"runs-workflow":           true,
	"scheduled-after":         true,
	"scheduled-before":        true,
	"steers":                  true,
	"summarizes":              true,
	"sync-target":             true,
	"synced-via":              true,
	"tagged":                  true,
	"tagged-in":               true,
	"ticks-on":                true,
	"tool-mounted-in-session": true,
	"tracks":                  true,
	"triggered-by":            true,
	"triggers":                true,
	"watched-by":              true,
	"watches":                 true,
	"{semantic}":              true,
}
