#!/usr/bin/env python3
"""
generate_type_map.py — generate moos-router --type-map flags from ontology.json

Reads kb/superset/ontology.json and emits --type-map type_id=URL flags grouped by
stratum. Edit the STRATUM_KERNELS mapping below to assign each stratum to a kernel.

Usage:
    python3 dev/scripts/generate_type_map.py [--ontology path] [--format shell|args|json]

Output formats:
    shell  (default) — shell snippet for moos-router startup scripts
    args             — bare --type-map flags, one per line
    json             — {"type_id": "kernel_url", ...} mapping

Theory:
    Type routing is a functor TypeID → KernelURL. Strata provide a natural
    partitioning: S0/S1 grammar types rarely change and live on a stable kernel;
    S2 infrastructure nodes belong to their workstation kernel; S3 interaction
    nodes may route to a specialised compute kernel.

    Inheritance: if a type routes to the same kernel as its stratum default,
    the --type-map flag is omitted (shard rules cover it). Only overrides are emitted.
"""

import json
import sys
import argparse
from pathlib import Path

# ─── Configure this mapping ──────────────────────────────────────────────────
# Map stratum → kernel base URL. Adjust to match your deployment.
# These are the defaults; override per type_id in OVERRIDES below.
STRATUM_KERNELS = {
    "S0": "http://localhost:8000",   # substrate: workstation, kernel, file
    "S1": "http://localhost:8000",   # grammar: type definitions, WF categories
    "S2": "http://localhost:8000",   # infrastructure: agent, session, channel, purpose
    "S3": "http://localhost:8000",   # interaction: tool_call, message_packet, knowledge_item
    "S4": "http://localhost:8000",   # projection: computed views (usually same kernel)
}

# Per-type overrides. type_id → kernel URL. Empty = use stratum default.
# Example: route all prg_task nodes to Z440 primary kernel.
# OVERRIDES = {
#     "prg_task": "http://hp-z440:8000",
#     "knowledge_item": "http://hp-z440:8001",
# }
OVERRIDES: dict[str, str] = {}

# ─────────────────────────────────────────────────────────────────────────────


def load_ontology(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def extract_types(ontology: dict) -> list[tuple[str, str]]:
    """Returns list of (type_id, stratum) from all type categories."""
    result = []
    for _category, types in ontology.get("types", {}).items():
        for t in types:
            type_id = t.get("id", "")
            stratum = t.get("stratum", "S2")
            if type_id:
                result.append((type_id, stratum))
    return result


def build_type_map(types: list[tuple[str, str]]) -> dict[str, str]:
    """Build type_id → kernel_url mapping, applying overrides."""
    mapping = {}
    for type_id, stratum in types:
        if type_id in OVERRIDES:
            mapping[type_id] = OVERRIDES[type_id]
        elif stratum in STRATUM_KERNELS:
            mapping[type_id] = STRATUM_KERNELS[stratum]
    return mapping


def format_shell(mapping: dict[str, str], group_by_stratum: list[tuple[str, str]]) -> str:
    """Shell snippet with types grouped by stratum and kernel."""
    # Group by target URL
    by_url: dict[str, list[str]] = {}
    strata: dict[str, str] = {tid: s for tid, s in group_by_stratum}
    for type_id, url in sorted(mapping.items()):
        by_url.setdefault(url, []).append(type_id)

    lines = ["# moos-router type-map flags — generated by generate_type_map.py", "# Edit STRATUM_KERNELS in the script to change kernel assignments.", ""]

    for url, type_ids in sorted(by_url.items()):
        lines.append(f"# → {url}")
        for tid in sorted(type_ids):
            s = strata.get(tid, "?")
            lines.append(f"  --type-map {tid}={url}  # {s}")
        lines.append("")

    return "\n".join(lines)


def format_args(mapping: dict[str, str]) -> str:
    """Bare --type-map flags, one per line."""
    lines = [f"--type-map {tid}={url}" for tid, url in sorted(mapping.items())]
    return "\n".join(lines)


def format_json(mapping: dict[str, str]) -> str:
    return json.dumps(mapping, indent=2, sort_keys=True)


def main():
    repo_root = Path(__file__).resolve().parents[2]
    default_ontology = repo_root / "kb" / "superset" / "ontology.json"

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ontology", default=str(default_ontology), help="path to ontology.json")
    parser.add_argument("--format", choices=["shell", "args", "json"], default="shell")
    args = parser.parse_args()

    try:
        ontology = load_ontology(args.ontology)
    except FileNotFoundError:
        print(f"error: ontology not found at {args.ontology}", file=sys.stderr)
        sys.exit(1)

    types = extract_types(ontology)
    if not types:
        print("error: no types found in ontology", file=sys.stderr)
        sys.exit(1)

    mapping = build_type_map(types)

    if args.format == "shell":
        print(format_shell(mapping, types))
    elif args.format == "args":
        print(format_args(mapping))
    elif args.format == "json":
        print(format_json(mapping))


if __name__ == "__main__":
    main()
